@Library("jenlib") _

try {
	wafDefaultPipeline(projects: ["tools-slurm"],
	                   container: [app            : "dev-tools",
	                               singularityArgs: "-B /run/nscd " +
	                                                "-B /run/munge"],
	                   enableClangFormat: false,
	                   notificationChannel: "#jenkins-trashbin")

	boolean deploy = env.GERRIT_EVENT_TYPE == "change-merged"
	conditionalStage(name: "Module Deployment", skip: !deploy) {
		runOnSlave(label: "frontend") {
			inSingularity(app: "dev-tools") {
				deployModule([name: "tools-slurm", source: "bin/ repos_log.txt"])
			}
		}
	}
} catch (Throwable t) {
	notifyFailure(mattermostChannel: "#softies")
	throw t
}

if (currentBuild.currentResult != "SUCCESS") {
	notifyFailure(mattermostChannel: "#softies")
}