@Library("jenlib") _

try {
	wafDefaultPipeline(projects: ["tools-slurm"],
	                   container: [app: "dev-tools"],
	                   notificationChannel: "#jenkins-trashbin")

	boolean deploy = env.GERRIT_EVENT_TYPE == "change-merged"
	conditionalStage(name: "Module Deployment", skip: !deploy) {
		runOnSlave(label: "frontend") {
			inSingularity(app: "dev-tools") {
				// Nothing to deploy yet, add 'bin/', 'lib/', ... to 'source' if appropriate
				deployModule([name: "tools-slurm", source: "repos_log.txt"])
			}
		}
	}
} catch (Throwable t) {
	notifyFailure(mattermostChannel: "#softies")
	throw t
}

if (currentBuild.currentResult != "SUCCESS") {
	notifyFailure(mattermostChannel: "#softies")
}